language: php
php:
  - 7.1
  - 7.2

services:
  - mariadb: '10.3'

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

before_script:
  - composer self-update
  - composer update --no-interaction

script:
  - vendor/bin/phpstan analyse -c phpstan.neon -l7 src/ tests/ --ansi
#  - mkdir tests/tmp && chmod 777 tests/tmp
  - vendor/bin/tester tests/
